server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-ct195pd6l47c73bdb1p0-a.oregon-postgres.render.com:5432/bdbarber
        username: bdbarber_user
        password: Z2jCWgmIlJkVwKy00OvoLxLuBlpNchVR
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
